[tool.poetry]
name = "tfdocs"
version = "0.1.0"
description = ""
authors = ["acrease <alex@crease.sh>"]
readme = "readme.md"
packages = [{include = "tfdocs"}]

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


