name: Publish on PyPI
description: Publish python artefacts to PyPI
inputs:
  pypi-token:
    required: true
    description: The PyPI API Key to use
  repository:
    required: false
    default: pypi
    description: Which python repository to upload to, use testpypi for the Test repos.
runs:
  using: composite
  steps:  
    - name: Publish to PyPI
      shell: bash
      env:
        TWINE_PASSWORD: ${{ inputs.pypi_token }}
        repository: ${{ inputs.repository }}
      run: |
        twine upload \
          --non-interactive \
          --repository $repository \
          dist/*
