name: Publish on PyPI
description: Publish python artefacts to PyPI
inputs:
  repository:
    required: false
    default: pypi
    description: Which python repository to upload to, use testpypi for the Test repos.
runs:
  using: composite
  steps:  
    - name: Publish to PyPI
      shell: bash
      env:
        repository: ${{ inputs.repository }}
      run: |
        twine upload \
          --non-interactive \
          --repository $repository \
          --verbose \
          dist/*
