name: Build for PyPI
description: Build TFDocs artefacts for PyPI publishing
runs:
  using: composite
  steps:
    - name: Setup Nix
      uses: ./.github/actions/nix-setup

    - shell: bash
      run: |
        poetry build

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
        name: tfdocs-pypi
