name: Release
description: Tag the current commit based on the branch
inputs:
  token:
    required: true
    description: Github token to use
runs:
  using: composite
  steps:
    - uses: ./.github/actions/nix-setup
    - name: Create new tag
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git fetch --prune --tags
        git pull

        branch_name=$(git rev-parse --abbrev-ref HEAD)
        # find most recent tag on the branch
        tag=$(git tag --merged | tail -n 1)
        # if no tag can be found, use 0.0.0
        if [[ $tag -eq "" ]]; then
          tag="0.0.0"
        fi
        preid="none"
        # if branch name is dev, do a patch increment
        if [[ "$branch_name" = "dev" ]]; then
          inc="patch"
        # if branch name is main, do a minor increment
        elif [[ "$branch_name" = "main" ]]; then
          inc="minor"
        elif [[ "$branch_name" = "release" ]]; then
          inc="preminor"
          preid="rc"
        else
          inc="prerelease"
          preid="pr"
        fi
        # use semver to increment it by one
        new_tag=$(semver -i $inc --preid $preid $tag)
        new_tag="v$new_tag"
        if [[ "$preid" = "none" ]]; then
          tidy_tag=$new_tag
        else
          tidy_tag=$(semver -i $new_tag)
          echo $tidy_tag
        fi
        poetry version "$tidy_tag"
        git add pyproject.toml
        git commit --amend --no-edit
        git push origin
        echo "Previous tag: $tag"
        echo "Incrementing by $inc on $branch_name"
        echo "Got new tag: $new_tag"
        # create a new tag
        git tag $new_tag
        git push origin --tags


