name: Setup Nix
description: Sets up Nix and the Nix store in a job
runs:
  using: "composite"
  steps:
    # - uses: nixbuild/nix-quick-install-action@v27

    # - name: Restore and cache Nix store
    #   uses: nix-community/cache-nix-action@v5
    #   with:
    #     primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
    #     restore-prefixes-first-match: nix-${{ runner.os }}-
    #     gc-max-store-size-linux: 1073741824
    #     purge: true
    #     purge-prefixes: cache-${{ runner.os }}-
    #     purge-created: 0
    #     purge-primary-key: never

    - name: "Setup env"
      uses: JRMurr/direnv-nix-action@v4.1.0
      # with:
        # You already installed nix, so you can disable that step
        # install-nix: "false"
