name: Dev PR Checks

# Triggers
on:
  pull_request:
    branches:
      - dev
  merge_group:

# All jobs must pass before merge
jobs:
  flake-cache:
    name: Build Nix Store
    uses: ./.github/workflows/build-cache.yaml
    permissions: write-all
  code-ci:
    name: Code CI Workflows
    permissions: write-all
    needs: [flake-cache]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Test Python code
        uses: ./.github/actions/just
        with:
          cmd: py-test-cov-full
      # - name: Commit changes
      #   uses: ./.github/actions/commit
      #   with:
      #     message: "chore: lint code"
      #     token: ${{secrets.GITHUB_TOKEN}}
        
