name: Dev PR Checks

# Triggers
on:
  pull_request:
    branches:
      - dev
  merge_group:

# All jobs must pass before merge
jobs:

  flake-cache:
    name: Build Nix Store
    uses: ./.github/workflows/build-cache.yaml
    permissions: write-all

  sync-environment:
    name: Sync Terraform Environment
    uses: ./.github/workflows/sync-env.yaml

  code-ci:
    name: Code CI Workflows
    permissions: write-all
    needs: [flake-cache]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Test Python code
        uses: ./.github/actions/just
        with:
          cmd: py-test-cov-full
        
  tf-plan:
    name: Terraform Plan
    permissions: write-all
    secrets: inherit
    uses: ./.github/workflows/tf-plan.yaml
