name: Dev Branch Merge

# Triggers
on:
  pull_request:
    branches:
      - dev
    types:
      - closed
  merge_group:

jobs:
  apply-plan:
    # if: github.event.pull_request.merge == true
    permissions: write-all
    name: Apply Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - uses: ./.github/actions/nix-setup

      - name: Terraform Apply
        run: |
          unset AWS_PROFILE
          terraform init
          terraform apply plan
        env:
          TF_VAR_ENV: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Commit Apply
        uses: ./.github/actions/commit
        with:
          message: "ci: terraform apply"
          token: ${{ secrets.GITHUB_TOKEN }}
