name: Dev Branch Merge

# Triggers
on:
  pull_request:
    branches:
      - dev
    types:
      - closed
  merge_group:

jobs:
  apply-plan:
    # if: github.event.pull_request.merge == true
    permissions: write-all
    name: Apply Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          fetch-depth: 0

      - uses: ./.github/actions/nix-setup

      - name: Terraform Apply
        run: |
          unset AWS_PROFILE
          terraform init
          terraform apply plan
        env:
          TF_VAR_ENV: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Git user
        shell: bash
        run: |
          git config pull.rebase true
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git add .
          git commit -m "ci: Terraform Apply"

      - name: Push Changes to Dev
        run: |
          git push origin dev
