name: Publish to PyPI
on:
  workflow_call:
    inputs:
      test_repo:
        required: false
        default: pypi
        type: string
# permissions:
#   id-token: write
jobs:
  publish-pypi:
    name: Publish on PyPI
    runs-on: ubuntu-24.04
    environment: 
      name: ${{inputs.test_repo && 'testpypi' || 'pypi' }}
      url: ${{ inputs.test_repo && 'https://test.pypi.org/p/tfdocs' || 'https://pypi.org/p/tfdocs' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/nix-setup

      - name: Download PyPI Artefacts
        uses: actions/download-artifact@v4
        with:
          name: tfdocs-pypi
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ inputs.test_repo && 'https://test.pypi.org/legacy/' || 'https://pypi.org/legacy/' }}
          verbose: true
