name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-py:
    name: Create PyPI Artefacts
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-py

  build-appimage:
    name: Create AppImage Build
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Run Build
        uses: ./.github/actions/build-appimage

  # build-macos:
  #   name: Build App for MacOS
  #   runs-on: macos-latest-large
  #   permissions: write-all
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run Build for MacOS
  #       uses: ./.github/actions/build-macos
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         path: tfdocs.app
  #         name: tfdocs-macos

  # build-win:
  #   name: Build EXE for Windows
  #   runs-on: windows-latest
  #   permissions: write-all
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run Build for Windows
  #       uses: ./.github/actions/build-win
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         path: tfdocs.exe
  #         name: tfdocs-win

  create-release:
    name: Publish Release
    runs-on: ubuntu-24.04
    needs:
      - build-appimage
      - build-py
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.BRANCH_BYPASS_KEY }}

      - name: Setup Nix
        uses: ./.github/actions/nix-setup

      # DOWNLOAD BUILDS

      - name: Download AppImage
        uses: actions/download-artifact@v4
        with:
          name: tfdocs-appimage
          path: .

      - name: Download PyPI Artefacts
        uses: actions/download-artifact@v4
        with:
          name: tfdocs-whl
          path: .

      - name: Download PyPI Artefacts
        uses: actions/download-artifact@v4
        with:
          name: tfdocs-src
          path: .

      - run: |
          ls
          stat tfdocs.AppImage

      # Create the release and upload builds

      - name: Create Release
        env:
          tag: ${{github.ref_name}}
          GH_TOKEN: ${{github.token}}
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          if [[ $branch -eq "main" ]]; then
            inc="Minor"
          elif [[ $branch -eq "dev" ]]; then
            inc="Patch"
            prerelease="--prerelease"
          else
            inc="PR Build"            
            prerelease="--prerelease"
          fi
          
          date=$(date +'%Y-%m-%d')
          title="TFDocs $tag"
          commit_msg=$(git show -s --format=%B "$tag")
          release_notes="$inc release of TFDocs, published on $date.\n $commit_msg"

          echo "Creating release $tag on branch $branch"

          # gh release create $tag
          gh release create "$tag" \
            $prerelease \
            --title "$title" \
            --notes "$release_notes" \
            tfdocs.AppImage \
            tfdocs-0.1.0-py3-none-any.whl \
            tfdocs-0.1.0.tar.gz


      # - name: Set current date
      #   run: echo "CURRENT_DATE=" >> $GITHUB_ENV

      # - uses: softprops/action-gh-release@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     body: |
      #       New release dated ${{env.CURRENT_DATE}}            
      #     fail_on_unmatched_files: true
      #     files: |
      #       tfdocs.appimage
          # tfdocs.app
          # tfdocs.exe
