name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-py:
    name: Create PyPI Artefacts
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Run Poetry Build
        uses: ./.github/actions/build-py

  build-appimage:
    name: Create AppImage Build
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Run Build AppImage
        uses: ./.github/actions/build-appimage

  # build-macos:
  #   name: Build App for MacOS
  #   runs-on: macos-latest-large
  #   permissions: write-all
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run Build for MacOS
  #       uses: ./.github/actions/build-macos
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         path: tfdocs.app
  #         name: tfdocs-macos

  # build-win:
  #   name: Build EXE for Windows
  #   runs-on: windows-latest
  #   permissions: write-all
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run Build for Windows
  #       uses: ./.github/actions/build-win
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         path: tfdocs.exe
  #         name: tfdocs-win

  publish-pypi:
    name: Publish on PyPI
    runs-on: ubuntu-24.04
    needs: build-py
    environment: 
      # use the test repo if it's an incremental tag
      name: ${{ contains(github.ref, '-') && 'testpypi' || 'pypi' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/nix-setup

      - name: Download PyPI Artefacts
        uses: actions/download-artifact@v4
        with:
          name: tfdocs-pypi
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ vars.PYPI_REPO_URL }}
          verbose: true

  upload-to-s3:
    if: ${{ !contains(github.ref, '-') }}
    name: Upload AppImage to artefact s3
    runs-on: ubuntu-24.04
    needs:
      - build-appimage
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/nix-setup

      - name: Download AppImage
        uses: actions/download-artifact@v4
        with:
          name: tfdocs-appimage
          path: .

      - name: Upload to storage bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket_name: tfdocs-dev-artefacts
          tag: ${{github.ref}}
        run: |
          unset AWS_PROFILE
          aws s3 cp build/tfdocs.AppImage s3://"$bucket_name"/"$tag"/tfdocs.AppImage


  create-release:
    name: Publish Release
    runs-on: ubuntu-24.04
    needs:
      - build-appimage
      - build-py
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.BRANCH_BYPASS_KEY }}

      - name: Setup Nix
        uses: ./.github/actions/nix-setup

      # DOWNLOAD BUILDS

      - name: Download AppImage
        uses: actions/download-artifact@v4
        with:
          name: tfdocs-appimage
          path: .

      - name: Download PyPI Artefacts
        uses: actions/download-artifact@v4
        with:
          name: tfdocs-pypi
          path: dist

      # Create the release and upload builds
      - name: Create Release
        env:
          tag: ${{github.ref_name}}
          GH_TOKEN: ${{github.token}}
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          echo $branch
          prerelease=""
          if [[ "$branch" == "main" ]]; then
            inc="Minor"
          elif [[ "$branch" == "dev" ]]; then
            inc="Patch"
            prerelease="--prerelease"
          else
            inc="PR Build"            
            prerelease="--prerelease --latest=false --draft"
          fi
          
          date=$(date +'%Y-%m-%d')
          title="TFDocs $tag"
          commit_msg=$(git show -s --format=%B "$tag")
          release_notes="$inc release of TFDocs, published on $date.
          Notes:
          $commit_msg"

          echo "Creating release $tag on branch $branch"

          # gh release create $tag
          cmd="gh release create \"${tag}\" \
            ${prerelease} \
            --title \"${title}\" \
            --notes \"${release_notes}\" \
            tfdocs.AppImage \
            dist/*"
          url=$({
            
            bash -c "$cmd"
          })

          echo "
          ***[New Release $tag]($url)***

          ---
          # $title
          $release_notes
          " >> $GITHUB_STEP_SUMMARY


