name: Terraform Plan
on:
  workflow_call:
    inputs:
      env:
        type: string
        default: dev
        description: The value to pass as TF_VAR_ENV
    outputs:
      diff:
        description: Whether or not the plan proposes any changes
        value: ${{ jobs.tf-plan.outputs.diff }}
jobs:
  tf-plan:
    name: Terraform Plan
    permissions: write-all
    runs-on: ubuntu-24.04
    outputs:
      diff: ${{ steps.check.outputs.diff }}
    defaults:
      run:
        working-directory: infra
    env:
      TF_VAR_ENV: ${{ inputs.env }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Nix
        uses: ./.github/actions/nix-setup

      - name: Terraform plan
        run: |
          unset AWS_PROFILE
          terraform init
          terraform plan -out=plan

      - name: Scan Generated Plan File
        uses: ./.github/actions/checkov-scan
        with:
          plan: true

      - uses: reproio/terraform-j2md@master
        with:
          version: v0.0.7

      - run: |
          terraform show -json plan \
          |  terraform-j2md \
          >> $GITHUB_STEP_SUMMARY
    
      - name: Scan Generated Plan File for Misconfigurations
        uses: ./.github/actions/checkov-scan
        with:
          plan: true

      - name: Upload plan as Artefact
        uses: actions/upload-artifact@v4
        with:
          name: plan
          path: infra/plan

      - name: Upload Web Source Zip as Artefact
        uses: actions/upload-artifact@v4
        with:
          name: Web-Source-Code
          path: infra/app.zip

      - id: check
        name: Check Plan for Changes
        run: |
          unset AWS_PROFILE
          terraform init
          line_count=$(terraform show plan | wc -l)
          if [ "$line_count" -gt 5 ]; then
            echo "Changes detected"
            echo "diff=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected"
            echo "diff=false" >> $GITHUB_OUTPUT
          fi
